[build]
target = "../../x86_64-atom-user.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
rustflags = [
    "-C", "relocation-model=static"
]
